USE `unlock`;
INSERT INTO card (`numCarte`, `image`, `image_back`, `type`, `use`, `require`) VALUES
                                                                                   ('6', '6.png', '6_back.png', 'blue', '[]', '["P1"]'),
                                                                                   ('8', '8.png', '8_back.png', 'grey', '["24"]', '["24"]'),
                                                                                   ('9', '9.png', '9_back.png', 'grey', '["6"]', '["6"]'),
                                                                                   ('15', '15.png', '15_back.png', 'blue', '[]', '["P1"]'),
                                                                                   ('20', '20.png', '20_back.png', 'grey', '[]', '["R"]'),
                                                                                   ('22', '22.png', '22_back.png', 'red', '[]', '["91"]'),
                                                                                   ('23', '23.png', '23_back.png', 'yellow', '["22"]', '["22"]'),
                                                                                   ('24', '24.png', '24_back.png', 'red', '[]', '["P1"]'),
                                                                                   ('28', '28.png', '28_back.png', 'grey', '["15","85"]', '["15"]'),
                                                                                   ('30', '30.png', '30_back.png', 'trap', '[]', '[]'),
                                                                                   ('37', '37.png', '37_back.png', 'trap', '[]', '[]'),
                                                                                   ('39', '39.png', '39_back.png', 'trap', '[]', '[]'),
                                                                                   ('42', '42.png', '42_back.png', 'grey', '[]', '["91"]'),
                                                                                   ('55', '55.png', '55_back.png', 'yellow', '[]', '["P1"]'),
                                                                                   ('60', '60.png', '60_back.png', 'yellow', '["23","42"]', '["23"]'),
                                                                                   ('66', '66.png', '66_back.png', 'blue', '[]', '["91"]'),
                                                                                   ('85', '85.png', '85_back.png', 'green', '[]', '["91"]'),
                                                                                   ('88', '88.png', '88_back.png', 'trap', '[]', '[]'),
                                                                                   ('91', '91.png', null, 'piece', '["P1","55","H","A","9","R","A","20"]', '["55","H","A","9","20"]'),
                                                                                   ('P1', 'p1.png', null, 'piece', '[]', '[]'),
                                                                                   ('A', 'A.png', 'A_back.png', 'grey', '["8"]', '["8"]'),
                                                                                   ('INTRO', 'intro.png', null, 'intro', '[]', '[]'),
                                                                                   ('B', 'B.png', 'B_back.png', 'trap', '[]', '[]'),
                                                                                   ('R', 'R.png', 'R_back.png', 'grey', '[]', '["P1"]'),
                                                                                   ('H', 'H.png', 'H_back.png', 'grey', '[]', '["P1"]');
